export const PROMPT_LIBRARY = [
  // ── MİDJOURNEY ──────────────────────────────────────────────
  {
    id: "mj-1",
    aiKey: "midjourney",
    aiName: "Midjourney v7",
    aiColor: "#3B82F6",
    category: "image",
    categoryLabel: "Görsel",
    title: "Japon Bahçesi",
    prompt: "Sabah sisi içinde ahşap köprü, Japon bahçesi, cherry blossom ağaçları, pastel renkler, sinematik --ar 16:9 --stylize 400",
  },
  {
    id: "mj-2",
    aiKey: "midjourney",
    aiName: "Midjourney v7",
    aiColor: "#3B82F6",
    category: "image",
    categoryLabel: "Görsel",
    title: "Şehir Neon Manzarası",
    prompt: "Minimalist şehir manzarası, gece neon ışıkları, yağmurlu asfalt yansıması, siber punk stili --ar 9:16 --stylize 500",
  },
  {
    id: "mj-3",
    aiKey: "midjourney",
    aiName: "Midjourney v7",
    aiColor: "#3B82F6",
    category: "image",
    categoryLabel: "Görsel",
    title: "Parfüm Ürün Fotoğrafı",
    prompt: "Profesyonel ürün fotoğrafı, parfüm şişesi, beyaz mermer yüzey, yumuşak stüdyo ışığı, şık ve temiz --ar 1:1 --stylize 250",
  },
  {
    id: "mj-4",
    aiKey: "midjourney",
    aiName: "Midjourney v7",
    aiColor: "#3B82F6",
    category: "image",
    categoryLabel: "Görsel",
    title: "Bioluminescent Orman",
    prompt: "Fantastik orman, bioluminescent bitkiler, gece sahnesi, mavi-yeşil parıltılar, sinematik wide shot --ar 21:9 --stylize 600",
  },
  {
    id: "mj-5",
    aiKey: "midjourney",
    aiName: "Midjourney v7",
    aiColor: "#3B82F6",
    category: "image",
    categoryLabel: "Görsel",
    title: "Minimalist Logo",
    prompt: "Soyut logo tasarımı, geometrik şekiller, tek renk, flat white arka plan, vektör stili --ar 1:1 --no shadow texture",
  },

  // ── NANO BANANA (GEMİNİ) ────────────────────────────────────
  {
    id: "nb-1",
    aiKey: "nano-banana",
    aiName: "Nano Banana (Gemini)",
    aiColor: "#22C55E",
    category: "image",
    categoryLabel: "Görsel",
    title: "Kedi Portresi",
    prompt: "Gerçekçi kedi portresi, stüdyo ışıklandırması, beyaz arka plan, detaylı kürk dokusu, profesyonel fotoğraf kalitesi",
  },
  {
    id: "nb-2",
    aiKey: "nano-banana",
    aiName: "Nano Banana (Gemini)",
    aiColor: "#22C55E",
    category: "image",
    categoryLabel: "Görsel",
    title: "E-Ticaret Ürün Görseli",
    prompt: "E-ticaret ürün görseli, kahve fincanı, pastel sarı arka plan, gölgesiz, temiz ve sade kompozisyon",
  },
  {
    id: "nb-3",
    aiKey: "nano-banana",
    aiName: "Nano Banana (Gemini)",
    aiColor: "#22C55E",
    category: "image",
    categoryLabel: "Görsel",
    title: "Türk Kahvaltısı",
    prompt: "Türk kahvaltısı sofrası, kuş bakışı çekim, ahşap masa, doğal güneş ışığı, yemek fotoğrafçılığı stili",
  },
  {
    id: "nb-4",
    aiKey: "nano-banana",
    aiName: "Nano Banana (Gemini)",
    aiColor: "#22C55E",
    category: "image",
    categoryLabel: "Görsel",
    title: "Tech Logo Konsepti",
    prompt: "Startup logo konsepti, modern ve sade, mavi-beyaz renk paleti, tech sektörü, vektör görünümü",
  },
  {
    id: "nb-5",
    aiKey: "nano-banana",
    aiName: "Nano Banana (Gemini)",
    aiColor: "#22C55E",
    category: "image",
    categoryLabel: "Görsel",
    title: "Film Estetiği Portre",
    prompt: "İnsan portresi, 35mm film estetiği, dışarıda doğal ışık, bokeh arka plan, samimi ifade",
  },

  // ── CHATGPT ─────────────────────────────────────────────────
  {
    id: "gpt-1",
    aiKey: "gpt-4o",
    aiName: "ChatGPT",
    aiColor: "#10A37F",
    category: "text",
    categoryLabel: "Metin",
    title: "Instagram Caption",
    prompt: "Sen deneyimli bir pazarlama uzmanısın. [Ürün adı] için Instagram'da 25-35 yaş arası kadınlara yönelik, samimi ve ilham verici tonda 5 farklı caption yaz. Her birini emoji ile bitir.",
  },
  {
    id: "gpt-2",
    aiKey: "gpt-4o",
    aiName: "ChatGPT",
    aiColor: "#10A37F",
    category: "text",
    categoryLabel: "Metin",
    title: "Metin Özetleme",
    prompt: "Aşağıdaki metni oku ve şunları yap: 1) 3 cümlelik özet, 2) 5 maddelik ana noktalar, 3) Hedef kitle için 1 önerilen eylem. Metin: [buraya yapıştır]",
  },
  {
    id: "gpt-3",
    aiKey: "gpt-4o",
    aiName: "ChatGPT",
    aiColor: "#10A37F",
    category: "text",
    categoryLabel: "Metin",
    title: "CV Hakkımda Bölümü",
    prompt: "[Pozisyon] için CV'me ekleyecek güçlü bir 'Hakkımda' bölümü yaz. Deneyimim: [kısaca anlat]. Ton: profesyonel ama samimi. Maksimum 150 kelime.",
  },
  {
    id: "gpt-4",
    aiKey: "gpt-4o",
    aiName: "ChatGPT",
    aiColor: "#10A37F",
    category: "text",
    categoryLabel: "Metin",
    title: "Haftalık İçerik Takvimi",
    prompt: "Benim için bir haftalık içerik takvimi oluştur. Sektör: [sektörün]. Platform: Instagram. Günde 1 gönderi. Her gün için: konu başlığı, format (reels/carousel/post) ve kısa açıklama.",
  },
  {
    id: "gpt-5",
    aiKey: "gpt-4o",
    aiName: "ChatGPT",
    aiColor: "#10A37F",
    category: "text",
    categoryLabel: "Metin",
    title: "E-Posta Yeniden Yazma",
    prompt: "Şu e-postayı daha profesyonel ve net bir dille yeniden yaz, abartılı nezaket ifadelerini kaldır: [e-posta metni]",
  },

  // ── CLAUDE ──────────────────────────────────────────────────
  {
    id: "claude-1",
    aiKey: "claude-sonnet",
    aiName: "Claude Sonnet",
    aiColor: "#D97757",
    category: "text",
    categoryLabel: "Metin",
    title: "Kod İnceleme ve Düzeltme",
    prompt: "Aşağıdaki kodu adım adım incele. Her hatayı numaralandırarak açıkla ve düzeltilmiş versiyonu yorumlarla birlikte döndür: [kod bloğu]",
  },
  {
    id: "claude-2",
    aiKey: "claude-sonnet",
    aiName: "Claude Sonnet",
    aiColor: "#D97757",
    category: "text",
    categoryLabel: "Metin",
    title: "Blog Yazısı Taslağı",
    prompt: "[Konu] hakkında kapsamlı bir blog yazısı taslağı çıkar. Yapı: giriş, 4 ana bölüm (her birinde 3 alt başlık), sonuç. SEO'ya uygun H2/H3 başlıkları kullan.",
  },
  {
    id: "claude-3",
    aiKey: "claude-sonnet",
    aiName: "Claude Sonnet",
    aiColor: "#D97757",
    category: "text",
    categoryLabel: "Metin",
    title: "UX Mikro-Kopya",
    prompt: "Sen bir UX yazarısın. Aşağıdaki uygulama ekranı için kullanıcı dostu, kısa ve net mikro-kopya metinleri yaz: buton metinleri, hata mesajları, onboarding açıklamaları. Ekran: [açıkla]",
  },
  {
    id: "claude-4",
    aiKey: "claude-sonnet",
    aiName: "Claude Sonnet",
    aiColor: "#D97757",
    category: "text",
    categoryLabel: "Metin",
    title: "Veri Analizi Raporu",
    prompt: "Bu veri setini analiz et ve şunları çıkar: 1) Temel istatistikler, 2) En dikkat çekici 3 bulgu, 3) Olası nedenler, 4) Önerilen aksiyonlar. Veri: [yapıştır]",
  },
  {
    id: "claude-5",
    aiKey: "claude-sonnet",
    aiName: "Claude Sonnet",
    aiColor: "#D97757",
    category: "text",
    categoryLabel: "Metin",
    title: "Kod Geliştirme Görevi",
    prompt: "[Dil/framework] kullanarak şunu yap: [görev]. Gereksinimler: temiz kod, yorum satırları, hata yönetimi. Önce ne yapacağını 3 adımda açıkla, sonra kodu yaz.",
  },

  // ── GEMİNİ PRO ──────────────────────────────────────────────
  {
    id: "gemini-1",
    aiKey: "gemini-pro",
    aiName: "Gemini 2.5 Pro",
    aiColor: "#8B5CF6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Doküman Analizi",
    prompt: "Bu dokümanı oku. Önce 1 sayfalık yönetici özeti yaz, sonra şu soruları cevapla: [sorular]. Son olarak 3 kritik bulgu ve 3 öneri listele.",
  },
  {
    id: "gemini-2",
    aiKey: "gemini-pro",
    aiName: "Gemini 2.5 Pro",
    aiColor: "#8B5CF6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "SWOT Analizi",
    prompt: "[Şirket/ürün adı] için SWOT analizi yap. Her bölümde minimum 4 madde. Kaynakların güncel bilgiye dayalı olduğunu belirt. Sonunda 1 stratejik öncelik öner.",
  },
  {
    id: "gemini-3",
    aiKey: "gemini-pro",
    aiName: "Gemini 2.5 Pro",
    aiColor: "#8B5CF6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Excel Veri Analizi",
    prompt: "Aşağıdaki verileri analiz et. Hangi ürün/kategori en iyi performans gösteriyor? Trend var mı? Görselleştirmek için hangi grafik tipini önerirsin ve neden? Veri: [yapıştır]",
  },
  {
    id: "gemini-4",
    aiKey: "gemini-pro",
    aiName: "Gemini 2.5 Pro",
    aiColor: "#8B5CF6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Sektör Araştırması",
    prompt: "[Konu/sektör] hakkında kapsamlı bir araştırma yap. Mevcut durum, önemli oyuncular, trendler ve 2026 öngörüleri şeklinde yapılandırılmış rapor sun.",
  },
  {
    id: "gemini-5",
    aiKey: "gemini-pro",
    aiName: "Gemini 2.5 Pro",
    aiColor: "#8B5CF6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Akademik Makale Özeti",
    prompt: "Bu makaleyi oku ve şu formatta özetle: Amaç (1 cümle), Yöntem (2-3 cümle), Bulgular (5 madde), Sonuç (2 cümle). Teknik terimleri basit dille açıkla.",
  },

  // ── PERPLEXITY ──────────────────────────────────────────────
  {
    id: "perp-1",
    aiKey: "perplexity",
    aiName: "Perplexity",
    aiColor: "#14B8A6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Sektör Güncel Gelişmeler",
    prompt: "2025-2026 yıllarında [sektör/konu] alanındaki en önemli gelişmeler nelerdir? Kaynakları ve tarihleri belirt.",
  },
  {
    id: "perp-2",
    aiKey: "perplexity",
    aiName: "Perplexity",
    aiColor: "#14B8A6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Ürün Karşılaştırması",
    prompt: "[Ürün/hizmet A] ile [Ürün/hizmet B] arasındaki farklar nelerdir? Fiyat, özellik ve kullanıcı yorumları açısından güncel karşılaştırma yap.",
  },
  {
    id: "perp-3",
    aiKey: "perplexity",
    aiName: "Perplexity",
    aiColor: "#14B8A6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Akademik Çalışmalar",
    prompt: "[Konu] hakkında son 6 ayda yapılan akademik çalışmalar var mı? Varsa ana bulguları özetle ve kaynak bağlantılarını paylaş.",
  },
  {
    id: "perp-4",
    aiKey: "perplexity",
    aiName: "Perplexity",
    aiColor: "#14B8A6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Marka Haberleri ve Yorumları",
    prompt: "[Şirket/marka] hakkında son haberleri ve kullanıcı yorumlarını özetle. Olumlu ve olumsuz geri bildirimleri ayrı listele.",
  },
  {
    id: "perp-5",
    aiKey: "perplexity",
    aiName: "Perplexity",
    aiColor: "#14B8A6",
    category: "research",
    categoryLabel: "Araştırma",
    title: "Yasal Gereksinimler",
    prompt: "[Şehir/ülke]'de [iş/yatırım türü] yapmak için yasal gereksinimler nelerdir? Güncel mevzuat ve prosedürleri açıkla.",
  },

  // ── SUNO AI ─────────────────────────────────────────────────
  {
    id: "suno-1",
    aiKey: "suno",
    aiName: "Suno AI",
    aiColor: "#A855F7",
    category: "music",
    categoryLabel: "Müzik",
    title: "Motivasyon Pop",
    prompt: "Upbeat pop, kadın vokal, 120 BPM, motivasyon temalı İngilizce şarkı, elektro gitar, nakarat odaklı yapı",
  },
  {
    id: "suno-2",
    aiKey: "suno",
    aiName: "Suno AI",
    aiColor: "#A855F7",
    category: "music",
    categoryLabel: "Müzik",
    title: "Türkçe Ayrılık Ballad",
    prompt: "Türkçe akustik ballad, erkek vokal, yavaş tempo, melankoli, ayrılık temalı, piyano ve keman",
  },
  {
    id: "suno-3",
    aiKey: "suno",
    aiName: "Suno AI",
    aiColor: "#A855F7",
    category: "music",
    categoryLabel: "Müzik",
    title: "Lo-fi Çalışma Müziği",
    prompt: "Lo-fi hip hop, enstrümantal, yağmur sesi arka planda, çalışma ve odaklanma müziği, sakin ve tekrarlı ritim",
  },
  {
    id: "suno-4",
    aiKey: "suno",
    aiName: "Suno AI",
    aiColor: "#A855F7",
    category: "music",
    categoryLabel: "Müzik",
    title: "Epik Film Müziği",
    prompt: "Epik orkestral, film müziği tarzı, dramatik crescendo, keman ve trompet, 2 dakikalık sahne müziği",
  },
  {
    id: "suno-5",
    aiKey: "suno",
    aiName: "Suno AI",
    aiColor: "#A855F7",
    category: "music",
    categoryLabel: "Müzik",
    title: "Türk Pop Dans",
    prompt: "Türk pop, genç kadın vokal, neşeli ve enerjik, yaz temalı, dans edilebilir ritim, modern prodüksiyon",
  },

  // ── MUZİCA ──────────────────────────────────────────────────
  {
    id: "muzica-1",
    aiKey: "muzica",
    aiName: "Muzica",
    aiColor: "#F97316",
    category: "music",
    categoryLabel: "Müzik",
    title: "Türkçe Aşk Şarkısı",
    prompt: "Türkçe pop, kadın vokal, aşk temalı, neşeli ve modern prodüksiyon, dans edilebilir, nakarat güçlü",
  },
  {
    id: "muzica-2",
    aiKey: "muzica",
    aiName: "Muzica",
    aiColor: "#F97316",
    category: "music",
    categoryLabel: "Müzik",
    title: "Anadolu Türküsü",
    prompt: "Akustik türkü tarzı, saz eşliğinde, Anadolu melodisi, hüzünlü erkek vokal, geleneksel Türk müziği estetiği",
  },
  {
    id: "muzica-3",
    aiKey: "muzica",
    aiName: "Muzica",
    aiColor: "#F97316",
    category: "music",
    categoryLabel: "Müzik",
    title: "Türkçe Rap",
    prompt: "Türkçe rap, kentsel beat, özgüvenli erkek vokal, motivasyon temalı sözler, trap prodüksiyon",
  },
  {
    id: "muzica-4",
    aiKey: "muzica",
    aiName: "Muzica",
    aiColor: "#F97316",
    category: "music",
    categoryLabel: "Müzik",
    title: "Çocuk Şarkısı",
    prompt: "Türkçe çocuk şarkısı, neşeli ve eğitici, basit melodiler, sevimli kadın vokal, anaokulu uyumlu",
  },
  {
    id: "muzica-5",
    aiKey: "muzica",
    aiName: "Muzica",
    aiColor: "#F97316",
    category: "music",
    categoryLabel: "Müzik",
    title: "Romantik Ballad",
    prompt: "Türkçe romantik ballad, yavaş tempo, piyano ve yaylılar, derin erkek vokal, düğün ve özel an teması",
  },

  // ── KLİNG AI ────────────────────────────────────────────────
  {
    id: "kling-1",
    aiKey: "kling-ai",
    aiName: "Kling 3.0",
    aiColor: "#F59E0B",
    category: "video",
    categoryLabel: "Video",
    title: "Ürün Reklamı",
    prompt: "Kahve fincanı beyaz mermer yüzey, buharlı içecek, yavaş dolly-in kamera, sabah ışığı, sinematik 5 saniye",
  },
  {
    id: "kling-2",
    aiKey: "kling-ai",
    aiName: "Kling 3.0",
    aiColor: "#F59E0B",
    category: "video",
    categoryLabel: "Video",
    title: "Şehir Drone Çekimi",
    prompt: "Büyük şehir silueti, gün batımı, yavaş pan right, altın saat ışığı, sinematik wide shot, drone rising",
  },
  {
    id: "kling-3",
    aiKey: "kling-ai",
    aiName: "Kling 3.0",
    aiColor: "#F59E0B",
    category: "video",
    categoryLabel: "Video",
    title: "Doğa Sahnesi",
    prompt: "Şelale ve yeşil orman, statik kamera, su akışı, kuşlar uçuyor arka planda, sakin ve huzurlu atmosfer",
  },
  {
    id: "kling-4",
    aiKey: "kling-ai",
    aiName: "Kling 3.0",
    aiColor: "#F59E0B",
    category: "video",
    categoryLabel: "Video",
    title: "Moda Yürüyüşü",
    prompt: "Kadın model şehirde yürüyor, ağır çekim, renkli kıyafet, taze ve modern estetik, pan left kamera",
  },
  {
    id: "kling-5",
    aiKey: "kling-ai",
    aiName: "Kling 3.0",
    aiColor: "#F59E0B",
    category: "video",
    categoryLabel: "Video",
    title: "Logo Animasyonu",
    prompt: "Logo beliriveriyor, parçacık efektleri, siyah arka plan, altın rengi, sinematik açılış sekansı, 5 saniye",
  },

  // ── VEO 3 ───────────────────────────────────────────────────
  {
    id: "veo-1",
    aiKey: "veo-3",
    aiName: "Google Veo 3.1",
    aiColor: "#EF4444",
    category: "video",
    categoryLabel: "Video",
    title: "Barista Kahve Sahnesi",
    prompt: "Bir barista kahve hazırlıyor, espresso makinesinin sesi, buhar sesi, close-up çekim, gerçekçi ses ve görüntü senkronizasyonu",
  },
  {
    id: "veo-2",
    aiKey: "veo-3",
    aiName: "Google Veo 3.1",
    aiColor: "#EF4444",
    category: "video",
    categoryLabel: "Video",
    title: "Sahil Günbatımı",
    prompt: "Sahil günbatımı sahnesi, dalga sesleri, hafif rüzgar, çocuklar koşuyor, belgesel tarzı doğal çekim",
  },
  {
    id: "veo-3",
    aiKey: "veo-3",
    aiName: "Google Veo 3.1",
    aiColor: "#EF4444",
    category: "video",
    categoryLabel: "Video",
    title: "Ürün Lansmanı",
    prompt: "Kutu açılıyor, içinden ürün çıkıyor, dramatik ışıklandırma, etkileyici arka plan müziği, unboxing hissi",
  },
  {
    id: "veo-4",
    aiKey: "veo-3",
    aiName: "Google Veo 3.1",
    aiColor: "#EF4444",
    category: "video",
    categoryLabel: "Video",
    title: "Kafe Diyaloğu",
    prompt: "İki kişi kafe ortamında konuşuyor, doğal diyalog sesi, samimi atmosfer, yumuşak arka plan bokeh, yakın plan",
  },
  {
    id: "veo-5",
    aiKey: "veo-3",
    aiName: "Google Veo 3.1",
    aiColor: "#EF4444",
    category: "video",
    categoryLabel: "Video",
    title: "Spor Motivasyon",
    prompt: "Koşucu parkurda, nefes sesi, ayak sesleri, motivasyonel atmosfer, ağır çekim anlık, enerjik müzik",
  },
];

export const CATEGORIES = [
  { id: "all", label: "Tümü" },
  { id: "image", label: "Görsel" },
  { id: "text", label: "Metin" },
  { id: "research", label: "Araştırma" },
  { id: "music", label: "Müzik" },
  { id: "video", label: "Video" },
];

export const AI_FILTERS = [
  { key: "all", name: "Tüm AI'lar" },
  { key: "midjourney", name: "Midjourney" },
  { key: "nano-banana", name: "Nano Banana" },
  { key: "gpt-4o", name: "ChatGPT" },
  { key: "claude-sonnet", name: "Claude" },
  { key: "gemini-pro", name: "Gemini Pro" },
  { key: "perplexity", name: "Perplexity" },
  { key: "suno", name: "Suno AI" },
  { key: "muzica", name: "Muzica" },
  { key: "kling-ai", name: "Kling AI" },
  { key: "veo-3", name: "Veo 3" },
];
